// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DatabaseFramework.Domain.Abstractions
{
    public partial interface ICheckConstraintContainer : CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.ICheckConstraintContainerBuilder>
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<DatabaseFramework.Domain.CheckConstraint> CheckConstraints
        {
            get;
        }
    }
    public partial interface IDatabaseObject : DatabaseFramework.Domain.Abstractions.ISchemaContainer, DatabaseFramework.Domain.Abstractions.INameContainer, CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.IDatabaseObjectBuilder>
    {
    }
    public partial interface IFileGroupNameContainer : CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.IFileGroupNameContainerBuilder>
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string FileGroupName
        {
            get;
        }
    }
    public partial interface INameContainer : CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.INameContainerBuilder>
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
        }
    }
    public partial interface INonViewField : DatabaseFramework.Domain.Abstractions.INameContainer, CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.INonViewFieldBuilder>
    {
        DatabaseFramework.Domain.Domains.SqlFieldType Type
        {
            get;
        }

        System.Nullable<byte> NumericPrecision
        {
            get;
        }

        System.Nullable<byte> NumericScale
        {
            get;
        }

        System.Nullable<int> StringLength
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string StringCollation
        {
            get;
        }

        System.Nullable<bool> IsStringMaxLength
        {
            get;
        }
    }
    public partial interface ISchemaContainer : CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.Abstractions.ISchemaContainerBuilder>
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [System.ComponentModel.DefaultValueAttribute(@"dbo")]
        string Schema
        {
            get;
        }
    }
}
#nullable disable
