// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DatabaseFramework.Domain.Builders.Abstractions
{
    public partial interface ICheckConstraintContainerBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.ObjectModel.ObservableCollection<DatabaseFramework.Domain.Builders.CheckConstraintBuilder> CheckConstraints
        {
            get;
            set;
        }

        DatabaseFramework.Domain.Abstractions.ICheckConstraintContainer Build();
    }
    public partial interface IDatabaseObjectBuilder : DatabaseFramework.Domain.Builders.Abstractions.ISchemaContainerBuilder, DatabaseFramework.Domain.Builders.Abstractions.INameContainerBuilder
    {
        new DatabaseFramework.Domain.Abstractions.IDatabaseObject Build();
    }
    public partial interface IFileGroupNameContainerBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string FileGroupName
        {
            get;
            set;
        }

        DatabaseFramework.Domain.Abstractions.IFileGroupNameContainer Build();
    }
    public partial interface INameContainerBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
            set;
        }

        DatabaseFramework.Domain.Abstractions.INameContainer Build();
    }
    public partial interface INonViewFieldBuilder : DatabaseFramework.Domain.Builders.Abstractions.INameContainerBuilder
    {
        DatabaseFramework.Domain.Domains.SqlFieldType Type
        {
            get;
            set;
        }

        System.Nullable<byte> NumericPrecision
        {
            get;
            set;
        }

        System.Nullable<byte> NumericScale
        {
            get;
            set;
        }

        System.Nullable<int> StringLength
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string StringCollation
        {
            get;
            set;
        }

        System.Nullable<bool> IsStringMaxLength
        {
            get;
            set;
        }

        new DatabaseFramework.Domain.Abstractions.INonViewField Build();
    }
    public partial interface ISchemaContainerBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [System.ComponentModel.DefaultValueAttribute(@"dbo")]
        string Schema
        {
            get;
            set;
        }

        DatabaseFramework.Domain.Abstractions.ISchemaContainer Build();
    }
}
#nullable disable
