// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DatabaseFramework.TemplateFramework
{
    public partial record DatabaseSchemaGeneratorSettings
    {
        public bool RecurseOnDeleteGeneratedFiles
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string LastGeneratedFilesFilename
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Text.Encoding Encoding
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string Path
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Globalization.CultureInfo CultureInfo
        {
            get;
        }

        public bool GenerateMultipleFiles
        {
            get;
        }

        public bool SkipWhenFileExists
        {
            get;
        }

        public bool CreateCodeGenerationHeader
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string FilenameSuffix
        {
            get;
        }

        public DatabaseSchemaGeneratorSettings(bool recurseOnDeleteGeneratedFiles, string lastGeneratedFilesFilename, System.Text.Encoding encoding, string path, System.Globalization.CultureInfo cultureInfo, bool generateMultipleFiles, bool skipWhenFileExists, bool createCodeGenerationHeader, string filenameSuffix)
        {
            this.RecurseOnDeleteGeneratedFiles = recurseOnDeleteGeneratedFiles;
            this.LastGeneratedFilesFilename = lastGeneratedFilesFilename;
            this.Encoding = encoding;
            this.Path = path;
            this.CultureInfo = cultureInfo;
            this.GenerateMultipleFiles = generateMultipleFiles;
            this.SkipWhenFileExists = skipWhenFileExists;
            this.CreateCodeGenerationHeader = createCodeGenerationHeader;
            this.FilenameSuffix = filenameSuffix;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public DatabaseFramework.TemplateFramework.Builders.DatabaseSchemaGeneratorSettingsBuilder ToBuilder()
        {
            return new DatabaseFramework.TemplateFramework.Builders.DatabaseSchemaGeneratorSettingsBuilder(this);
        }
    }
}
#nullable disable
