// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DatabaseFramework.Domain
{
    public abstract partial record SqlStatementBase
    {
        protected SqlStatementBase()
        {
        }

        public abstract DatabaseFramework.Domain.Builders.SqlStatementBaseBuilder ToBuilder();
    }
}
#nullable disable
