// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DatabaseFramework.Domain
{
    public abstract partial record SqlStatementBase : CrossCutting.Common.Abstractions.IBuildableEntity<DatabaseFramework.Domain.Builders.SqlStatementBaseBuilder>
    {
        protected SqlStatementBase()
        {
        }

        public static implicit operator DatabaseFramework.Domain.Builders.SqlStatementBaseBuilder(DatabaseFramework.Domain.SqlStatementBase entity)
        {
            return entity.ToBuilder();
        }

        public abstract DatabaseFramework.Domain.Builders.SqlStatementBaseBuilder ToBuilder();
    }
}
#nullable disable
